import {readFile,writeFile,mkdir,cp} from 'node:fs/promises';
import {cardHTML,escapeHTML as e,disciplines} from '../assets/catalog.mjs';
const data=JSON.parse(await readFile('data/portfolio.json','utf8'));
let index=await readFile('index.html','utf8');
const cards=data.projects.filter(p=>p.featured).map(p=>cardHTML(p)).join('\n');
index=index.replace(/<div id="featured" class="project-grid">[\s\S]*?<\/div><noscript>/,`<div id="featured" class="project-grid">${cards}</div><noscript>`);
await writeFile('index.html',index);
await mkdir('projects',{recursive:true});
const dialog=index.match(/<dialog[\s\S]*?<\/dialog>/)[0];
for(const p of data.projects){
  const url=`https://andrea-borzi.github.io/projects/${p.slug}.html`;
  const image=p.thumb.startsWith('http')?p.thumb:`https://andrea-borzi.github.io/${p.thumb}`;
  const src=p.thumb.startsWith('http')?p.thumb:'../'+p.thumb;
  let direct=p.act==='video'?`https://www.youtube.com/watch?v=${p.arg}`:p.act==='shorts'?`https://www.instagram.com/p/${data.instagram[p.arg][0]}/`:p.act==='link'?p.arg:p.act==='single'?'../'+p.arg:null;
  const context=p.arg==='tuttomotori'?'Una collaborazione su una serie editoriale dedicata al mondo automotive. Ogni video è consultabile nell’archivio: scegli il titolo che vuoi esplorare.':p.arg==='urbanheroes'?'Una selezione di contenuti social. Puoi scegliere uno dei 29 post oppure aprirlo direttamente su Instagram.':p.title==='Zodiac'?'Un progetto personale dedicato all’atmosfera di una sequenza di apertura. Tipografia, movimento e 3D sono gli elementi del linguaggio visivo.':p.act==='single'&&p.meta.includes('AR')?'Questa scheda presenta una tavola del progetto AR. L’immagine documenta il lavoro; non avvia un’esperienza di realtà aumentata.':p.act==='photo'?'Una serie fotografica da esplorare immagine per immagine. La galleria permette di scegliere lo scatto e passare al successivo.':p.act==='link'?'Un progetto interattivo da esplorare nel suo ambiente originale. Il collegamento apre una nuova scheda.':p.description;
  const page=`<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(p.title)} — Andrea Borzì</title><meta name="description" content="${e(context)}"><link rel="canonical" href="${url}"><meta property="og:type" content="article"><meta property="og:title" content="${e(p.title)} — Andrea Borzì"><meta property="og:description" content="${e(context)}"><meta property="og:image" content="${e(image)}"><meta property="og:url" content="${url}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="../favicon.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,500;12..96,700;12..96,800&family=Outfit:wght@300;400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/site.css"><script src="../assets/site.js" type="module"></script></head><body><header class="nav"><a class="brand" href="../index.html">AB<span class="brand-dot">*</span><span class="brand-name">ANDREA BORZÌ<br><small>VISUAL ARTIST</small></span></a><nav aria-label="Menu principale"><a href="../index.html#work">Tutti i lavori</a><a class="nav-contact" href="../index.html#contact">Parliamone ↗</a></nav></header><main class="project-page wrap"><span class="eyebrow">${e(disciplines[p.disc])} / ${e(p.kind)}</span><h1>${e(p.title)}</h1><p class="intro">${e(context)}</p><div class="project-still${p.arg==='urbanheroes'?' urban-still':''}"><img src="${e(src)}" alt="${e(p.title)}" width="1280" height="720"></div><dl>${p.role?`<dt>Il mio contributo</dt><dd>${e(p.role)}</dd>`:''}<dt>Linguaggio</dt><dd>${e(p.meta)}</dd></dl><div class="actions"><button class="button" data-open="${e(p.slug)}">${p.act==='photo'?'Esplora la serie':p.act==='single'?'Guarda l’immagine':p.act==='link'?'Apri il progetto':'Guarda i contenuti'} ↗</button>${direct?`<a class="button outline" href="${e(direct)}" target="_blank" rel="noopener">Apri direttamente ↗</a>`:''}</div><noscript><p>Per aprire la galleria attiva JavaScript. I collegamenti diretti rimangono disponibili.</p></noscript><div class="archive-bar"><p>Hai un progetto in mente?</p><a class="text-link" href="mailto:borzi.andrea98@gmail.com?subject=${encodeURIComponent('Un progetto con Andrea — '+p.title)}">Parliamone ↗</a></div></main><footer class="wrap"><a href="../index.html#work">← Torna ai lavori</a><span>ANDREA BORZÌ · VISUAL ARTIST</span></footer>${dialog}</body></html>`;
  await writeFile(`projects/${p.slug}.html`,page);
}
const urls=['https://andrea-borzi.github.io/',...data.projects.map(p=>`https://andrea-borzi.github.io/projects/${p.slug}.html`)];
await writeFile('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(url=>`  <url><loc>${url}</loc></url>`).join('\n')}\n</urlset>\n`);
console.log(`Generate ${data.projects.length} pagine progetto e ${data.projects.filter(p=>p.featured).length} schede statiche.`);
await mkdir('_site',{recursive:true});
for(const item of ['index.html','assets','data','img','projects','favicon.png','robots.txt','sitemap.xml','social-preview.png']){
  await cp(item,`_site/${item}`,{recursive:true});
}
await writeFile('_site/.nojekyll','');
